services:
  - type: web
    name: hepatocai-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    headers:
      - key: Cache-Control
        value: public, max-age=31536000, immutable
        path: /assets/*
      - key: Cache-Control
        value: public, max-age=0, must-revalidate
        path: /
      - key: X-Frame-Options
        value: DENY
      - key: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /auth/callback
        destination: /index.html
      - type: rewrite
        source: /robots.txt
        destination: /robots.txt
      # Catch all other routes and serve index.html (SPA routing)
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /diagnosis
        destination: /index.html
      - type: rewrite
        source: /profile
        destination: /index.html
      - type: rewrite
        source: /admin/*
        destination: /index.html

      # Catch-all route (must be last)
      - type: rewrite
        source: /*
        destination: /index.html
