services:
  - type: web
    name: hepatocai-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    headers:
      - key: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /auth/callback
        destination: /index.html
      - type: rewrite
        source: /signin
        destination: /index.html
      - type: rewrite
        source: /signup
        destination: /index.html
